#!/usr/bin/env bash

# Heya! If you want to improve the code, fix bugs, or add new features make a PR on the github repo! https://github.com/talwat/pokeget
# Code written by Talwat :D

# Color variables

#GREEN="\x1B[32m"
YELLOW="\x1B[33m"
#ORANGE="\e[33m"
CYAN="\x1B[36m"
RED="\x1B[31m"
BOLD="\x1B[1m"
RESET="\x1B[0m"

# Configurable

small=false        # The default size value.
shiny=false        # The default shiny value.
back=false         # The default back value.
debug=false        # The default debug value.
variant=""         # The default variant value.

# Make config file.

if [ ! -d "$HOME/.config/pokeget" ]; then
  mkdir "$HOME/.config/pokeget"
fi
if [ ! -f "$HOME/.config/pokeget/pokeget.conf" ]; then
  printf "# Determines wether the sprite is the small (pc/box) sprite. Doesn't work with 'shiny' and 'back'.
small=false

# Determines wether the sprite will use the shiny variant.
shiny=false

# Determines wether the sprite will be facing backwards.
back=false

# The variant of the sprite. Determines megas, pokemon specific things like arceus, alolan forms, etc...
variant=\"\"
" >"$HOME/.config/pokeget/pokeget.conf"
fi

source "$HOME/.config/pokeget/pokeget.conf"

# Non-configurable variables

variantAsk=false
rawid=0

# Get Flags & Input

for var in "$@"; do
  case $var in
  -small)
    small=true
    ;;
  -big)
    small=false
    ;;
  -shiny)
    shiny=true
    ;;
  -notshiny)
    shiny=false
    ;;
  -back)
    back=true
    ;;
  -front)
    back=false
    ;;
  -variant)
    variantAsk=true
    ;;
  -debug)
    debug=true
    ;;
  -*)
    echo -e "${RED}[!]${RESET} Invalid flag"
    exit
    ;;
  *)
    if [ $variantAsk == true ]; then
      variant="${var}"
      variantAsk=false
    elif [ "$var" == "random" ]; then
      rawid=$((RANDOM % 807 + 0))
    else
      rawid=$var
    fi
    ;;
  esac
done

# Do stuff based on input

if [ "$1" == "" ]; then
  echo -e "${CYAN}[!]${RESET} Use ${BOLD}pokeget help${RESET} to see usage."
  exit 0

# Help Command

elif [ "$1" == "help" ]; then
  echo -e "${BOLD}pokeget${RESET} [flags] <pokemon ID/pokemon name>"
  echo -e "${BOLD}PS${RESET}: This program requires internet to work."
  echo ""
  echo -e "${BOLD}${CYAN}Commands${RESET}"
  echo -e "  ${BOLD}help:${RESET}           Displays this menu."
  echo -e "  ${BOLD}update:${RESET}         Updates pokeget."
  echo -e "  ${BOLD}uninstall:${RESET}      Uninstalls pokeget."
  echo -e "${BOLD}${CYAN}Flags${RESET}"
  echo -e "  ${BOLD}-small:${RESET}         Makes the pokemon a smaller sprite. in the pokemon games, this would be the sprite found when browsing the pokemon storage system."
  echo -e "  ${BOLD}-big:${RESET}           Makes the pokemon a big sprite. in the pokemon games, this would be the sprite found of your opponents pokemon while battling."
  echo -e "  ${BOLD}-back:${RESET}          Makes the pokemon the back sprite. in the pokemon games, this would be the sprite found of your pokemon while battling. Only works on big sprites."
  echo -e "  ${BOLD}-back:${RESET}          Makes the pokemon the front sprite. in the pokemon games, this would be the sprite found of your opponents pokemon while battling. Only works on big sprites."
  echo -e "  ${BOLD}-shiny:${RESET}         Dictates wether the pokemon is shiny, only works on big sprites. (NOTE: the shiny colors are from pokemon reborn, so a lot of them are completely different than the normal shiny colors.)"
  echo -e "  ${BOLD}-notshiny:${RESET}      Makes the pokemon not shiny."
  echo -e "  ${BOLD}-variant <num>:${RESET} This flag dictates the following things: wether the pokemon is mega, alolan form, pokemon specific things such as arceus, and a few other things."
  echo -e "${BOLD}${CYAN}Credits${RESET}"
  echo "  Pokeget now gets its sprites from Pokemon Reborn, which is why there may be some pokemon that look different."
  echo "  All sprites and art are originally made by gamefreak, so huge props to them."
  echo "  Code written by Talwat in bash."
  exit 0

elif [ "$1" == "update" ]; then
  bash <(curl -s https://raw.githubusercontent.com/talwat/pokeget/main/scripts/install.sh)

elif [ "$1" == "uninstall" ]; then
  bash <(curl -s https://raw.githubusercontent.com/talwat/pokeget/main/scripts/uninstall.sh)

else
  # Check if the input is a national dex ID or a pokemon name.

  if [[ $rawid =~ ^[0-9]+$ ]]; then
    isPkmnName=false
  else
    isPkmnName=true
  fi

  # Parse the ID/Name

  if [ $isPkmnName == false ]; then
    id=$rawid
    length=${#id}

    while ((length < 3)); do
      id=0$id
      length=${#id}
    done
  else
    id=$(echo "$rawid" | tr '[:upper:]' '[:lower:]')
  fi

  # Apply values from flags & config file

  if [ $small == true ]; then
    size="small"
    shiny=false
  else
    size="big"
    if [ $shiny == true ]; then
      id="${id}s"
    fi
    if [ $back == true ]; then
      id="${id}b"
    fi
  fi
  if [ "$variant" != "" ]; then
    id="${id}_${variant}"
  fi

  # Put together URL based on wether the input is an ID or a Name.
  if [ $isPkmnName == false ]; then
    url="https://raw.githubusercontent.com/talwat/pokeget/main/pokemon/${size}/${id}.txt"
  else
    url="https://raw.githubusercontent.com/talwat/pokeget/main/pokemon_named/${size}/${id}.txt"
  fi
  r=$(curl -s -L "${url}")
  if [ $debug == true ]; then
    echo -e "${YELLOW}[!]${RESET} $url"
  fi

  # Print output or 404 message

  if [[ $r == *"404"* ]]; then
    echo -e "${RED}[!]${RESET} Pokemon could not be found (404 Error)$RESET"
    exit 1
  else
    echo -e "$r$RESET"
    exit 0
  fi
fi
